### ISSUE TITLE
Difference in behavior between explicit and implicit [NotNull]

### ISSUE THREAD

**Issue by cmeeren** [ulrichb/ImplicitNullability#13]
Please see the following two images. In the first image, the parameter `id` is implicitly `NotNull`. ReSharper dims the null check and says it's unnecessary because `id` is never null. In the second image, I've added an explicit `[NotNull]` annotation and everything works as expected. I would expect the behavior to be the same in the two cases.

![without-annotations](https://cloud.githubusercontent.com/assets/7766733/25952112/017a1216-3660-11e7-886f-77da45dc34e6.PNG)

![with-annotation](https://cloud.githubusercontent.com/assets/7766733/25952113/017c3e38-3660-11e7-90dc-5792d967130a.PNG)

**Comment by ulrichb** [comment]
Thanks for your report. Unfortunately there isn't much I can do about it because it has to be solved within R#.

I created a bug report: https://youtrack.jetbrains.com/issue/RSRP-464760. Note that it happens even without Implicit Nullability for _inherited_ `[NotNull]`s.

At the moment, I can only suggest suppression comments or old-style (pre C#7) null checks as workarounds.

**Comment by cmeeren** [comment]
Thanks! I'll follow that bug report then.

**Comment by ulrichb** [comment]
Fixed in R# 2017.2
