### ISSUE TITLE
AssemblyMetadata in .NET < 4.5?

### ISSUE THREAD

**Issue by cmeeren** [ulrichb/ImplicitNullability#14]
I tried creating a .NET 4.0 project. Unfortunately, the `AssemblyMetadata` attribute does not seem to exist. Is there an alternative?

**Comment by ulrichb** [comment]
Yes, [`AssemblyMetadata`](https://msdn.microsoft.com/en-us/library/system.reflection.assemblymetadataattribute.aspx) is only available in .NET >= 4.5.

But it works also with a "user defined" attribute with the same FullName:
```C#
namespace System.Reflection
{
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
    public sealed class AssemblyMetadataAttribute : Attribute
    {
        public AssemblyMetadataAttribute(string key, string value) { }
    }
}
```

**Comment by cmeeren** [comment]
Thanks. Does it have to be defined in `System.Reflection`?

**Comment by ulrichb** [comment]
Yes.

On 31 May 2017 5:11 a.m., "Christer van der Meeren" <
notifications@github.com> wrote:

Thanks. Does it have to be defined in System.Reflection?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/ulrichb/ImplicitNullability/issues/14#issuecomment-305070016>,
or mute the thread
