### ISSUE TITLE
Support for "Nullable reference types"

### ISSUE THREAD

**Issue by rolandh** [ulrichb/ImplicitNullability#21]
If I install "Nullable reference types" preview resharper gives me lots of errors as it doesn't support this addition yet.

Does your plugin fix this and allow this code to not throw a warning?

`string? canBeNull = null;`

**Comment by ulrichb** [comment]
If you get ReSharper errors for the nullable reference types, then this is simply because R#'s C# model doesn't support this feature atm. Sorry, you have to wait until this is supported. Contact JetBrains to ask for a timeline. 

Implicit Nullability cannot do anything here and will never "support" nullable reference types, because this C# feature will "supersede" IN.

I would suggest to disable R# analysis in these projects.
