### ISSUE TITLE
support something that achieves the following Func<[NotNull]string>

### ISSUE THREAD

**Issue by rolandh** [ulrichb/ImplicitNullability#22]
As per my SO question here:
https://stackoverflow.com/questions/49247474/tell-resharper-that-a-funcstring-will-never-return-null

```
[NotNull]
private readonly Func<string> FunctionThatWillNeverBeNullNorReturnNull;

void Test(){
    string thisStringIsNotNull = FunctionThatWillNeverBeNullNorReturnNull();
}
```

Is it possible to tell resharper that the above function will never return null? Putting [NotNull] implies that the Function reference cannot be null, but I'm unsure how to tell resharper that what it returns won't be null either. Is this something you could support with your plugin?

**Comment by ulrichb** [comment]
This is not possible for "anonymous" (generic Func/Action) delegates.

But you could use named delegates. See [these examples](https://github.com/ulrichb/ImplicitNullability/blob/83b838480664bf6e4a7f34c7c097d8a468c0e146/Src/ImplicitNullability.Samples.CodeWithIN/NullabilityAnalysis/DelegatesSample.cs#L70-L97).

To support generic delegates, ReSharper would have to support a different means of nullability annotation (e.g. using comments). But I think its unrealistic to get implemented because with C# 8 nullable reference types this situation will work anyways (in the future).
