### ISSUE TITLE
Use assembly/class level attribute to enable this with some level of granularity

### ISSUE THREAD

**Issue by drewnoakes** [ulrichb/ImplicitNullability#3]
As mentioned here:

https://youtrack.jetbrains.com/issue/RSRP-68137

> Could be be opt-in at the class or assembly level via an attribute? This would then carry over in compiled builds.

**Comment by ulrichb** [comment]
In the [InheritedNullabilityAndExternalCodeIN](https://github.com/ulrichb/ImplicitNullability/tree/feature/InheritedNullabilityAndExternalCodeIN) branch I am working on exactly this feature (utilizing an `[assembly: AssemblyMetadata(...)]` attribute so that it will "carry over in compiled builds").

At the moment I have only a [pre-release for R# 9.2](https://resharper-plugins.jetbrains.com/packages/ReSharper.ImplicitNullability/2.5.0-beta1) of this feature.

But I definitely plan to finish this and release it together with the R# 2016.1 support. I cannot give any guarantees, but it will be Soon™.

**Comment by drewnoakes** [comment]
Glad to hear it's all underway. I'd like to remove the zillions of
[NotNull] attributes in my solution.

**Comment by ulrichb** [comment]
You can test the "compiled configuration attribute" feature now in a [pre-release version](https://resharper-plugins.jetbrains.com/packages/ReSharper.ImplicitNullability/3.0.0.20161-beta1) for R# 2016.1.

**Comment by drewnoakes** [comment]
Great, I'll take a look. As you mentioned on another issue, it'll be interesting to see how this works with the new R# option for implicity NotNull in 2016.1.

**Comment by ulrichb** [comment]
The released version 3.0.0 now supports [assembly-level configuration attributes](https://github.com/ulrichb/ImplicitNullability#configuration).

**Comment by drewnoakes** [comment]
Fantastic news. Thanks very much.
